site_name: Test docs
site_description: 'A docs test'
site_author: 'Björn Schotte'
docs_dir: docs/
repo_name: 'BjoernSchotte/docsers'
repo_url: 'https://github.com/BjoernSchotte/docsers'
nav:
    - Home: index.md
theme:
  name: 'material'
